In [2]:
import pandas as pd
from statcan_wds import get_table_data
import json
import yaml

In [3]:
def load_cfg(path, fmt="yaml"):
    if fmt == "yaml" or fmt == "yml":
        with open(path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    elif fmt == "json":
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

### Consumer Price Index, monthly, seasonally adjusted [pid: 18100006]

In [5]:
cpi_cfg = load_cfg(path="examples/cpi_adjusted.yaml")

In [7]:
cpi_df = get_table_data(
    pid=cpi_cfg["pid"],
    query_spec=cpi_cfg["query"],
    start_ref_period="2020-01-01",
    end_ref_period=None
)

In [11]:
cpi_df.head()

  Geography Products and product groups    REF_DATE  VALUE
0    Canada                   All-items  2020-01-01  137.5
1    Canada                   All-items  2020-02-01  137.7
2    Canada                   All-items  2020-03-01  136.3
3    Canada                   All-items  2020-04-01  135.6
4    Canada                   All-items  2020-05-01  135.4

### Canada Mortgage and Housing Corporation (average rents for areas with a population of 10,000 and over) [pid: 34100133]

In [30]:
cmhc_cfg = load_cfg(path="examples/cmhc.yaml")

In [31]:
cmhc_df = get_table_data(
    pid=cmhc_cfg["pid"],
    query_spec=cmhc_cfg["query"],
    start_ref_period=cmhc_cfg["start_ref_period"],
    end_ref_period=cmhc_cfg["end_ref_period"]
)

In [32]:
cmhc_df.head(10)

,Geography,Type of structure,Type of unit,REF_DATE,VALUE
0,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2020-01-01,443.0
1,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2021-01-01,504.0
2,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2022-01-01,512.0
3,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2023-01-01,526.0
4,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2024-01-01,580.0
5,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2025-01-01,658.0
6,"Montréal, Quebec",Row and apartment structures of three units an...,Bachelor units,2020-01-01,702.0
7,"Montréal, Quebec",Row and apartment structures of three units an...,Bachelor units,2021-01-01,712.0
8,"Montréal, Quebec",Row and apartment structures of three units an...,Bachelor units,2022-01-01,785.0
9,"Montréal, Quebec",Row and apartment structures of three units an...,Bachelor units,2023-01-01,810.0