In [1]:
import pandas as pd
from statcan_wds import get_table_data
import json
import yaml

In [2]:
def load_cfg(path, fmt="yaml"):
    if fmt == "yaml" or fmt == "yml":
        with open(path, "r", encoding="utf-8") as f:
            return yaml.safe_load(f)
    elif fmt == "json":
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)

### Consumer Price Index, monthly, seasonally adjusted [pid: 18100006]

In [3]:
cpi_cfg = load_cfg(path="examples/cpi_adjusted.yaml")

In [4]:
cpi_df = get_table_data(
    pid=cpi_cfg["pid"],
    query_spec=cpi_cfg.get("query", None),
    ref_start=cpi_cfg.get("ref_start", None),
    ref_end=cpi_cfg.get("ref_end", None)
)

In [5]:
cpi_df.head()

  Geography Products and product groups    REF_DATE  VALUE
0    Canada                   All-items  2025-01-01  162.5
1    Canada                   All-items  2025-02-01  163.5
2    Canada                   All-items  2025-03-01  163.5
3    Canada                   All-items  2025-04-01  163.1
4    Canada                   All-items  2025-05-01  163.5

### Canada Mortgage and Housing Corporation (average rents for areas with a population of 10,000 and over) [pid: 34100133]

In [6]:
cmhc_cfg = load_cfg(path="examples/cmhc.yaml")

In [7]:
cmhc_df = get_table_data(
    pid=cmhc_cfg["pid"],
    query_spec=cmhc_cfg.get("query", None),
    ref_start=cmhc_cfg.get("ref_start", None),
    ref_end=cmhc_cfg.get("ref_end", None)
)

In [9]:
cmhc_df.head()

,Geography,Type of structure,Type of unit,REF_DATE,VALUE
0,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2020-01-01,443.0
1,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2021-01-01,504.0
2,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2022-01-01,512.0
3,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2023-01-01,526.0
4,"Saguenay, Quebec",Row and apartment structures of three units an...,Bachelor units,2024-01-01,580.0

### Employment income statistics by occupation, major field of study and highest level of education: Canada [pid: 98100412]

In [10]:
empl_income_cfg = load_cfg(path="examples/empl_income.yaml")

In [11]:
empl_income_df = get_table_data(
    pid=empl_income_cfg["pid"],
    query_spec=empl_income_cfg.get("query", None),
    ref_start=empl_income_cfg.get("ref_start", None),
    ref_end=empl_income_cfg.get("ref_end", None)
)

In [12]:
empl_income_df

,Geography,Gender (3),Age (4),"Highest certificate, diploma or degree (16)",Major field of study - Classification of Instructional Programs (CIP) 2021 (63),Work activity during the reference year (4A),Occupation - Unit group - National Occupational Classification (NOC) 2021 (821A),Employment income statistics (7),REF_DATE,VALUE
0,Canada,Total - Gender,Total - Age,"Total - Highest certificate, diploma or degree",Total - Major field of study - Classification ...,Total - Work activity during the reference year,Total - Occupation - Unit group - National Occ...,Total - Employment income statistics,2021-01-01,30335915.0